<?php

namespace Database\Seeders;

use App\Models\Employer;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EmployerSeeder extends Seeder
{
    public function run(): void
    {
        $password = Hash::make('123456');
        $now = now();

        $employers = [
            [
                'user_name' => 'Nguyễn Văn Phong',
                'user_email' => 'phong.nguyen@thucphamviet.vn',
                'user_phone' => '0965200001',
                'company_name' => 'Công ty TNHH Thực phẩm Việt',
                'industry' => 'Thực phẩm',
                'company_size' => '500-1000',
                'tax_code' => '0301234567',
                'address' => '88 Đường Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 1',
                'contact_name' => 'Nguyễn Văn Phong',
                'contact_phone' => '0965200001',
                'description' => 'Công ty chuyên sản xuất, chế biến và phân phối thực phẩm sạch. Hệ thống nhà hàng và dịch vụ ăn uống công nghiệp phục vụ hơn 10.000 suất ăn/ngày.',
                'website' => 'https://thucphamviet.vn',
                'rating' => 4.3,
                'verified' => true,
            ],
            [
                'user_name' => 'Trần Minh Đức',
                'user_email' => 'duc.tran@sunrisehotel.vn',
                'user_phone' => '0965200002',
                'company_name' => 'Khách sạn Sunrise',
                'industry' => 'Khách sạn',
                'company_size' => '200-500',
                'tax_code' => '0401567890',
                'address' => '120 Đường Võ Nguyên Giáp, Sơn Trà, Đà Nẵng',
                'city' => 'Đà Nẵng',
                'district' => 'Sơn Trà',
                'contact_name' => 'Trần Minh Đức',
                'contact_phone' => '0965200002',
                'description' => 'Khách sạn 4 sao view biển Mỹ Khê, 150 phòng. Dịch vụ hội nghị, nhà hàng buffet và spa cao cấp.',
                'website' => 'https://sunrisehotel.vn',
                'rating' => 4.5,
                'verified' => true,
            ],
            [
                'user_name' => 'Lê Thanh Hằng',
                'user_email' => 'hang.le@megamart.vn',
                'user_phone' => '0965200003',
                'company_name' => 'Siêu thị MegaMart',
                'industry' => 'Bán lẻ',
                'company_size' => '1000+',
                'tax_code' => '0101234890',
                'address' => '25 Đường Láng Hạ, Ba Đình, Hà Nội',
                'city' => 'Hà Nội',
                'district' => 'Ba Đình',
                'contact_name' => 'Lê Thanh Hằng',
                'contact_phone' => '0965200003',
                'description' => 'Chuỗi siêu thị bán lẻ với 50 cửa hàng trên toàn quốc. Chuyên cung cấp hàng tiêu dùng, thực phẩm và đồ gia dụng chất lượng cao.',
                'website' => 'https://megamart.vn',
                'rating' => 4.1,
                'verified' => true,
            ],
            [
                'user_name' => 'Phạm Quốc Anh',
                'user_email' => 'anh.pham@phoxanh.vn',
                'user_phone' => '0965200004',
                'company_name' => 'Nhà hàng Phố Xanh',
                'industry' => 'F&B',
                'company_size' => '50-200',
                'tax_code' => '0102345678',
                'address' => '15 Phố Tạ Hiện, Hoàn Kiếm, Hà Nội',
                'city' => 'Hà Nội',
                'district' => 'Hoàn Kiếm',
                'contact_name' => 'Phạm Quốc Anh',
                'contact_phone' => '0965200004',
                'description' => 'Chuỗi nhà hàng ẩm thực Việt Nam truyền thống với 5 chi nhánh tại Hà Nội. Phục vụ món ăn Bắc Bộ đặc trưng và cocktail sáng tạo.',
                'website' => 'https://phoxanh.vn',
                'rating' => 4.4,
                'verified' => true,
            ],
            [
                'user_name' => 'Huỳnh Thị Ngọc Trâm',
                'user_email' => 'tram.huynh@bienxanh.vn',
                'user_phone' => '0965200005',
                'company_name' => 'Resort Biển Xanh',
                'industry' => 'Du lịch',
                'company_size' => '200-500',
                'tax_code' => '4201234567',
                'address' => '68 Đường Trần Phú, Vĩnh Hải, Nha Trang',
                'city' => 'Nha Trang',
                'district' => 'Vĩnh Hải',
                'contact_name' => 'Huỳnh Thị Ngọc Trâm',
                'contact_phone' => '0965200005',
                'description' => 'Resort 5 sao bên bờ biển Nha Trang, 200 phòng villa và bungalow. Hồ bơi vô cực, spa, nhà hàng hải sản và các hoạt động thể thao biển.',
                'website' => 'https://bienxanhresort.vn',
                'rating' => 4.7,
                'verified' => true,
            ],
            [
                'user_name' => 'Võ Minh Trí',
                'user_email' => 'tri.vo@anninhsg.vn',
                'user_phone' => '0965200006',
                'company_name' => 'Công ty An Ninh Sài Gòn',
                'industry' => 'Bảo vệ',
                'company_size' => '500-1000',
                'tax_code' => '0302345678',
                'address' => '200 Đường Điện Biên Phủ, Bình Thạnh, TP. Hồ Chí Minh',
                'city' => 'Hồ Chí Minh',
                'district' => 'Bình Thạnh',
                'contact_name' => 'Võ Minh Trí',
                'contact_phone' => '0965200006',
                'description' => 'Công ty dịch vụ bảo vệ chuyên nghiệp, cung cấp nhân viên an ninh cho tòa nhà, khu công nghiệp, sự kiện và vận chuyển tiền mặt.',
                'website' => 'https://anninhsaigon.vn',
                'rating' => 4.0,
                'verified' => true,
            ],
            [
                'user_name' => 'Đặng Thị Minh Châu',
                'user_email' => 'chau.dang@fpt.vn',
                'user_phone' => '0965200007',
                'company_name' => 'FPT Software',
                'industry' => 'CNTT',
                'company_size' => '5000+',
                'tax_code' => '0301456789',
                'address' => 'FPT Tower, 10 Phạm Văn Bạch, Tân Bình, TP. Hồ Chí Minh',
                'city' => 'Hồ Chí Minh',
                'district' => 'Tân Bình',
                'contact_name' => 'Đặng Thị Minh Châu',
                'contact_phone' => '0965200007',
                'description' => 'Công ty phần mềm hàng đầu Việt Nam, chuyên phát triển phần mềm, chuyển đổi số và dịch vụ CNTT cho khách hàng toàn cầu.',
                'website' => 'https://fpt-software.com',
                'rating' => 4.6,
                'verified' => true,
            ],
            [
                'user_name' => 'Nguyễn Đình Khoa',
                'user_email' => 'khoa.nguyen@vingroup.net',
                'user_phone' => '0965200008',
                'company_name' => 'Vingroup',
                'industry' => 'Bất động sản',
                'company_size' => '5000+',
                'tax_code' => '0100567890',
                'address' => 'Vinhomes Riverside, Long Biên, Hà Nội',
                'city' => 'Hà Nội',
                'district' => 'Long Biên',
                'contact_name' => 'Nguyễn Đình Khoa',
                'contact_phone' => '0965200008',
                'description' => 'Tập đoàn kinh tế tư nhân lớn nhất Việt Nam, hoạt động trong lĩnh vực bất động sản, bán lẻ, du lịch, giáo dục, y tế và công nghệ.',
                'website' => 'https://vingroup.net',
                'rating' => 4.5,
                'verified' => true,
            ],
            [
                'user_name' => 'Lý Quang Huy',
                'user_email' => 'huy.ly@tiki.vn',
                'user_phone' => '0965200009',
                'company_name' => 'Tiki Corporation',
                'industry' => 'TMĐT',
                'company_size' => '500-1000',
                'tax_code' => '0303456789',
                'address' => '52 Út Tịch, Tân Bình, TP. Hồ Chí Minh',
                'city' => 'Hồ Chí Minh',
                'district' => 'Tân Bình',
                'contact_name' => 'Lý Quang Huy',
                'contact_phone' => '0965200009',
                'description' => 'Sàn thương mại điện tử hàng đầu Việt Nam với hệ thống kho vận TikiNOW giao hàng trong 2 giờ. Hơn 10 triệu sản phẩm.',
                'website' => 'https://tiki.vn',
                'rating' => 4.2,
                'verified' => true,
            ],
            [
                'user_name' => 'Bùi Hồng Sơn',
                'user_email' => 'son.bui@masan.vn',
                'user_phone' => '0965200010',
                'company_name' => 'Masan Group',
                'industry' => 'FMCG',
                'company_size' => '5000+',
                'tax_code' => '0304567890',
                'address' => 'Central Tower, 24 Nguyễn Trung Trực, Quận 1, TP. Hồ Chí Minh',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 1',
                'contact_name' => 'Bùi Hồng Sơn',
                'contact_phone' => '0965200010',
                'description' => 'Tập đoàn hàng tiêu dùng - bán lẻ hàng đầu Việt Nam, sở hữu thương hiệu Chin-su, Nam Ngư, Kokomi, Omachi và chuỗi WinMart.',
                'website' => 'https://masan.vn',
                'rating' => 4.3,
                'verified' => true,
            ],
        ];

        foreach ($employers as $e) {
            // Create user with role employer
            $user = User::create([
                'name' => $e['user_name'],
                'email' => $e['user_email'],
                'phone' => $e['user_phone'],
                'password' => $password,
                'role' => 'employer',
                'status' => 'active',
                'email_verified_at' => $now,
                'last_login_at' => $now->copy()->subDays(rand(0, 7)),
            ]);

            // Create employer profile
            Employer::create([
                'user_id' => $user->id,
                'company_name' => $e['company_name'],
                'industry' => $e['industry'],
                'company_size' => $e['company_size'],
                'tax_code' => $e['tax_code'],
                'address' => $e['address'],
                'city' => $e['city'],
                'district' => $e['district'],
                'contact_name' => $e['contact_name'],
                'contact_phone' => $e['contact_phone'],
                'description' => $e['description'],
                'website' => $e['website'],
                'rating' => $e['rating'],
                'review_count' => rand(10, 100),
                'verified' => $e['verified'],
                'verified_at' => $e['verified'] ? $now->copy()->subDays(rand(30, 180)) : null,
            ]);
        }
    }
}
