<?php

namespace Database\Seeders;

use App\Models\Employer;
use App\Models\JobPost;
use Illuminate\Database\Seeder;

class JobPostSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // Fetch employers by company name
        $thucPhamViet = Employer::where('company_name', 'Công ty TNHH Thực phẩm Việt')->first();
        $sunrise = Employer::where('company_name', 'Khách sạn Sunrise')->first();
        $megaMart = Employer::where('company_name', 'Siêu thị MegaMart')->first();
        $phoXanh = Employer::where('company_name', 'Nhà hàng Phố Xanh')->first();
        $bienXanh = Employer::where('company_name', 'Resort Biển Xanh')->first();
        $anNinh = Employer::where('company_name', 'Công ty An Ninh Sài Gòn')->first();
        $fpt = Employer::where('company_name', 'FPT Software')->first();
        $vingroup = Employer::where('company_name', 'Vingroup')->first();
        $tiki = Employer::where('company_name', 'Tiki Corporation')->first();
        $masan = Employer::where('company_name', 'Masan Group')->first();

        $jobs = [
            // 1. Nhan vien phuc vu nha hang - Thuc pham Viet, HCM, active
            [
                'employer_id' => $thucPhamViet->id,
                'title' => 'Nhân viên phục vụ nhà hàng',
                'description' => "Vị trí: Nhân viên phục vụ tại hệ thống nhà hàng Thực phẩm Việt.\n\nMô tả công việc:\n- Đón tiếp, hướng dẫn khách hàng vào bàn\n- Tư vấn menu, nhận order và phục vụ món ăn\n- Dọn dẹp, vệ sinh khu vực bàn ăn\n- Hỗ trợ setup bàn tiệc, sự kiện\n- Kiểm tra chất lượng món ăn trước khi phục vụ\n- Giải quyết các yêu cầu và phản hồi của khách hàng",
                'requirements' => "- Nam/Nữ, tuổi từ 18-35\n- Ngoại hình ưa nhìn, gọn gàng\n- Có kỹ năng giao tiếp tốt\n- Chăm chỉ, nhanh nhẹn, có tinh thần làm việc nhóm\n- Ưu tiên có kinh nghiệm phục vụ nhà hàng\n- Sẵn sàng làm ca tối và cuối tuần",
                'benefits' => "- Lương cơ bản: 5.000.000 - 8.000.000 VNĐ/tháng\n- Bao ăn ca, đồng phục miễn phí\n- Tip phục vụ\n- BHXH, BHYT đầy đủ\n- Thưởng tháng 13, thưởng lễ tết\n- Cơ hội thăng tiến lên vị trí quản lý ca",
                'job_type' => 'full_time',
                'positions_count' => 5,
                'salary_type' => 'monthly',
                'salary_amount' => 6500000,
                'shift_type' => 'rotating',
                'work_start_date' => $now->copy()->subDays(10)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(6)->format('Y-m-d'),
                'work_address' => '88 Đường Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh',
                'has_housing' => false,
                'min_age' => 18,
                'max_age' => 35,
                'deadline' => $now->copy()->addDays(20)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 245,
            ],
            // 2. Le tan khach san - Sunrise, Da Nang, active
            [
                'employer_id' => $sunrise->id,
                'title' => 'Lễ tân khách sạn',
                'description' => "Vị trí: Lễ tân tại Khách sạn Sunrise 4 sao, Đà Nẵng.\n\nMô tả công việc:\n- Đón tiếp và check-in/check-out cho khách\n- Xử lý đặt phòng qua điện thoại, email và hệ thống online\n- Giải đáp thắc mắc và cung cấp thông tin du lịch cho khách\n- Điều phối các yêu cầu dịch vụ phòng\n- Xử lý thanh toán, hóa đơn\n- Phối hợp với bộ phận Housekeeping và F&B",
                'requirements' => "- Nam/Nữ, tuổi từ 20-30\n- Tốt nghiệp Cao đẳng/Đại học Du lịch hoặc Ngoại ngữ\n- Tiếng Anh giao tiếp tốt (TOEIC 550+)\n- Ngoại hình ưa nhìn, chiều cao nữ từ 1m58, nam từ 1m68\n- Kỹ năng giao tiếp và xử lý tình huống tốt\n- Sử dụng thành thạo tin học văn phòng",
                'benefits' => "- Lương: 6.000.000 - 10.000.000 VNĐ/tháng (theo kinh nghiệm)\n- Tip từ khách hàng\n- BHXH, BHYT, BHTN đầy đủ\n- Ăn ca miễn phí tại khách sạn\n- Phòng nghỉ miễn phí cho nhân viên xa nhà\n- Du lịch công ty hàng năm\n- Đào tạo nghiệp vụ khách sạn quốc tế",
                'job_type' => 'full_time',
                'positions_count' => 3,
                'salary_type' => 'monthly',
                'salary_amount' => 8000000,
                'shift_type' => 'rotating',
                'work_start_date' => $now->copy()->subDays(5)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(12)->format('Y-m-d'),
                'work_address' => '120 Đường Võ Nguyên Giáp, Sơn Trà, Đà Nẵng',
                'has_housing' => true,
                'min_age' => 20,
                'max_age' => 30,
                'deadline' => $now->copy()->addDays(15)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 312,
            ],
            // 3. Nhan vien ban hang - MegaMart, Ha Noi, active
            [
                'employer_id' => $megaMart->id,
                'title' => 'Nhân viên bán hàng',
                'description' => "Vị trí: Nhân viên bán hàng tại hệ thống Siêu thị MegaMart, Hà Nội.\n\nMô tả công việc:\n- Tư vấn, giới thiệu sản phẩm cho khách hàng\n- Sắp xếp, trưng bày hàng hóa đúng quy cách\n- Kiểm kê hàng tồn kho, báo cáo hàng thiếu\n- Thu ngân, xử lý thanh toán\n- Hỗ trợ nhập hàng, dán giá\n- Giữ gìn vệ sinh khu vực bán hàng",
                'requirements' => "- Nam/Nữ, tuổi từ 18-40\n- Không yêu cầu kinh nghiệm (được đào tạo)\n- Trung thực, cẩn thận, có tinh thần phục vụ\n- Có thể làm theo ca (sáng/chiều/tối)\n- Ưu tiên ứng viên có kinh nghiệm bán lẻ",
                'benefits' => "- Lương: 4.500.000 - 7.000.000 VNĐ/tháng\n- Phụ cấp ca tối, ngày lễ\n- BHXH, BHYT theo quy định\n- Chiết khấu mua hàng 10% cho nhân viên\n- Thưởng doanh số\n- Ca làm linh hoạt phù hợp sinh viên",
                'job_type' => 'part_time',
                'positions_count' => 10,
                'salary_type' => 'monthly',
                'salary_amount' => 5500000,
                'shift_type' => 'flexible',
                'work_start_date' => $now->copy()->subDays(15)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(3)->format('Y-m-d'),
                'work_address' => '25 Đường Láng Hạ, Ba Đình, Hà Nội',
                'has_housing' => false,
                'min_age' => 18,
                'max_age' => 40,
                'deadline' => $now->copy()->addDays(10)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 523,
            ],
            // 4. Phu bep nha hang - Pho Xanh, Ha Noi, active
            [
                'employer_id' => $phoXanh->id,
                'title' => 'Phụ bếp nhà hàng',
                'description' => "Vị trí: Phụ bếp tại chuỗi nhà hàng Phố Xanh, Hà Nội.\n\nMô tả công việc:\n- Hỗ trợ đầu bếp chuẩn bị nguyên liệu: rửa, cắt, sơ chế\n- Nấu các món ăn đơn giản theo công thức có sẵn\n- Dọn dẹp, vệ sinh khu vực bếp\n- Bảo quản thực phẩm đúng quy cách\n- Kiểm tra nguyên liệu đầu vào\n- Hỗ trợ bếp trưởng trong giờ cao điểm",
                'requirements' => "- Nam/Nữ, tuổi từ 18-40\n- Sức khỏe tốt, chịu được áp lực công việc\n- Có đam mê nấu ăn\n- Ưu tiên có kinh nghiệm phụ bếp hoặc đã qua trường nghề nấu ăn\n- Có chứng chỉ vệ sinh an toàn thực phẩm là lợi thế",
                'benefits' => "- Lương: 4.000.000 - 6.000.000 VNĐ/tháng\n- Bao ăn 3 bữa\n- BHXH, BHYT đầy đủ\n- Được đào tạo nghề bếp chuyên nghiệp\n- Cơ hội lên đầu bếp sau 1 năm\n- Thưởng lễ, Tết",
                'job_type' => 'full_time',
                'positions_count' => 2,
                'salary_type' => 'monthly',
                'salary_amount' => 5000000,
                'shift_type' => 'rotating',
                'work_start_date' => $now->copy()->subDays(7)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(6)->format('Y-m-d'),
                'work_address' => '15 Phố Tạ Hiện, Hoàn Kiếm, Hà Nội',
                'has_housing' => false,
                'min_age' => 18,
                'max_age' => 40,
                'deadline' => $now->copy()->addDays(12)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 156,
            ],
            // 5. Nhan vien don phong - Bien Xanh, Nha Trang, active
            [
                'employer_id' => $bienXanh->id,
                'title' => 'Nhân viên dọn phòng',
                'description' => "Vị trí: Nhân viên Housekeeping tại Resort Biển Xanh 5 sao, Nha Trang.\n\nMô tả công việc:\n- Dọn dẹp, vệ sinh phòng khách theo tiêu chuẩn 5 sao\n- Thay ga giường, khăn tắm, bổ sung amenities\n- Vệ sinh khu vực hành lang, lobby, hồ bơi\n- Giặt ủi đồ vải khách sạn\n- Báo cáo tình trạng phòng cho supervisor\n- Phối hợp với bộ phận lễ tân về lịch trả phòng",
                'requirements' => "- Nam/Nữ, tuổi từ 18-45\n- Sức khỏe tốt, cẩn thận, tỉ mỉ\n- Không yêu cầu kinh nghiệm (được đào tạo)\n- Chăm chỉ, trung thực, có ý thức kỷ luật\n- Ưu tiên có kinh nghiệm housekeeping khách sạn\n- Sẵn sàng làm việc theo mùa vụ du lịch",
                'benefits' => "- Lương: 5.000.000 - 7.500.000 VNĐ/tháng\n- Bao ăn, bao ở (ký túc xá nhân viên)\n- BHXH, BHYT đầy đủ\n- Tip từ khách\n- Phụ cấp mùa cao điểm\n- Du lịch nội bộ, tiệc nhân viên hàng quý",
                'job_type' => 'temporary',
                'positions_count' => 8,
                'salary_type' => 'monthly',
                'salary_amount' => 6000000,
                'shift_type' => 'day',
                'work_start_date' => $now->copy()->subDays(3)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(4)->format('Y-m-d'),
                'work_address' => '68 Đường Trần Phú, Vĩnh Hải, Nha Trang',
                'has_housing' => true,
                'min_age' => 18,
                'max_age' => 45,
                'deadline' => $now->copy()->addDays(25)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 389,
            ],
            // 6. Bao ve toa nha - An Ninh SG, HCM, active
            [
                'employer_id' => $anNinh->id,
                'title' => 'Bảo vệ tòa nhà',
                'description' => "Vị trí: Nhân viên bảo vệ tại các tòa nhà văn phòng và chung cư cao cấp, TP.HCM.\n\nMô tả công việc:\n- Tuần tra, kiểm soát an ninh khu vực được phân công\n- Kiểm tra giấy tờ, xe ra vào\n- Giám sát hệ thống camera an ninh\n- Xử lý các tình huống bất thường\n- Hỗ trợ PCCC khi có sự cố\n- Ghi nhật ký ca trực đầy đủ",
                'requirements' => "- Nam, tuổi từ 20-45\n- Chiều cao từ 1m65 trở lên\n- Sức khỏe tốt, không có tiền án tiền sự\n- Có chứng chỉ nghiệp vụ bảo vệ\n- Đã hoàn thành nghĩa vụ quân sự là lợi thế\n- Trung thực, kỷ luật, có tinh thần trách nhiệm cao",
                'benefits' => "- Lương: 5.500.000 - 8.000.000 VNĐ/tháng\n- Phụ cấp ca đêm, ngày lễ\n- BHXH, BHYT đầy đủ\n- Trang phục, dụng cụ bảo vệ\n- Bao ăn ca\n- Thưởng cuối năm 1-2 tháng lương",
                'job_type' => 'full_time',
                'positions_count' => 4,
                'salary_type' => 'monthly',
                'salary_amount' => 6500000,
                'shift_type' => 'rotating',
                'work_start_date' => $now->copy()->subDays(8)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(12)->format('Y-m-d'),
                'work_address' => '200 Đường Điện Biên Phủ, Bình Thạnh, TP. Hồ Chí Minh',
                'has_housing' => false,
                'min_age' => 20,
                'max_age' => 45,
                'gender_req' => 'Nam',
                'deadline' => $now->copy()->addDays(18)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 198,
            ],
            // 7. Lai xe giao hang - Tiki, HCM, active
            [
                'employer_id' => $tiki->id,
                'title' => 'Lái xe giao hàng',
                'description' => "Vị trí: Tài xế giao hàng TikiNOW tại TP. Hồ Chí Minh.\n\nMô tả công việc:\n- Nhận đơn hàng từ kho và giao đến khách hàng\n- Đảm bảo giao hàng đúng thời gian cam kết (2 giờ)\n- Kiểm tra đơn hàng trước khi giao\n- Thu tiền COD và nộp về công ty đúng quy định\n- Xử lý đơn hoàn trả, đổi hàng\n- Bảo quản hàng hóa cẩn thận trong quá trình vận chuyển",
                'requirements' => "- Nam, tuổi từ 20-40\n- Có bằng lái B2 hoặc C\n- Thông thạo đường phố TP.HCM\n- Có kinh nghiệm lái xe giao hàng ít nhất 1 năm\n- Không có tiền án tiền sự về vi phạm giao thông\n- Có smartphone để sử dụng app giao hàng",
                'benefits' => "- Lương cứng: 7.000.000 VNĐ + phụ cấp xăng + thưởng KPI\n- Thu nhập thực tế: 7.000.000 - 12.000.000 VNĐ/tháng\n- BHXH, BHYT đầy đủ\n- Hỗ trợ bảo trì phương tiện\n- Thưởng giao hàng đúng hẹn\n- Đồng phục, bảo hiểm hàng hóa",
                'job_type' => 'full_time',
                'positions_count' => 6,
                'salary_type' => 'monthly',
                'salary_amount' => 9000000,
                'shift_type' => 'day',
                'work_start_date' => $now->copy()->subDays(12)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(12)->format('Y-m-d'),
                'work_address' => '52 Út Tịch, Tân Bình, TP. Hồ Chí Minh',
                'has_housing' => false,
                'min_age' => 20,
                'max_age' => 40,
                'gender_req' => 'Nam',
                'deadline' => $now->copy()->addDays(30)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 467,
            ],
            // 8. Nhan vien kho - Masan, HCM, active
            [
                'employer_id' => $masan->id,
                'title' => 'Nhân viên kho',
                'description' => "Vị trí: Nhân viên kho vận tại hệ thống kho Masan, TP. Hồ Chí Minh.\n\nMô tả công việc:\n- Nhận hàng, kiểm đếm và nhập kho\n- Sắp xếp hàng hóa theo vị trí quy định\n- Xuất hàng theo đơn đặt hàng\n- Kiểm kê tồn kho định kỳ\n- Vận hành xe nâng (nếu có bằng)\n- Đảm bảo hàng hóa được bảo quản đúng quy cách",
                'requirements' => "- Nam, tuổi từ 18-40\n- Sức khỏe tốt, chịu khó\n- Có kinh nghiệm kho vận là lợi thế\n- Biết sử dụng phần mềm quản lý kho (WMS)\n- Có bằng lái xe nâng là ưu tiên\n- Trung thực, cẩn thận, có trách nhiệm",
                'benefits' => "- Lương: 5.000.000 - 8.000.000 VNĐ/tháng\n- Phụ cấp chuyên cần, phụ cấp tăng ca 150%\n- BHXH, BHYT, BHTN đầy đủ\n- Bao ăn trưa tại canteen\n- Thưởng tháng 13, thưởng KPI\n- Xe đưa đón nhân viên",
                'job_type' => 'full_time',
                'positions_count' => 5,
                'salary_type' => 'monthly',
                'salary_amount' => 6500000,
                'shift_type' => 'day',
                'work_start_date' => $now->copy()->subDays(6)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(12)->format('Y-m-d'),
                'work_address' => 'KCN Tân Phú Trung, Củ Chi, TP. Hồ Chí Minh',
                'has_housing' => true,
                'min_age' => 18,
                'max_age' => 40,
                'gender_req' => 'Nam',
                'deadline' => $now->copy()->addDays(14)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 278,
            ],
            // 9. Ky su phan mem - FPT, HCM, active
            [
                'employer_id' => $fpt->id,
                'title' => 'Kỹ sư phần mềm',
                'description' => "Vị trí: Software Engineer tại FPT Software, TP. Hồ Chí Minh.\n\nMô tả công việc:\n- Phát triển ứng dụng web theo yêu cầu khách hàng\n- Tham gia thiết kế kiến trúc hệ thống\n- Code review, viết unit test\n- Tham gia Agile/Scrum, daily standup\n- Làm việc với đội ngũ quốc tế\n- Nghiên cứu và áp dụng công nghệ mới",
                'requirements' => "- Tốt nghiệp Đại học CNTT hoặc tương đương\n- Có kinh nghiệm từ 1-3 năm phát triển phần mềm\n- Thành thạo ít nhất 1 ngôn ngữ: Java, C#, PHP, JavaScript/TypeScript\n- Hiểu biết về RESTful API, Database (SQL/NoSQL)\n- Tiếng Anh đọc hiểu tốt (giao tiếp là lợi thế)\n- Kỹ năng teamwork và giải quyết vấn đề tốt",
                'benefits' => "- Lương: 15.000.000 - 25.000.000 VNĐ/tháng\n- Thưởng dự án, thưởng năm 2-4 tháng lương\n- BHXH, BHYT, bảo hiểm FPTCare\n- Laptop công ty\n- Đào tạo và chứng chỉ quốc tế\n- Cơ hội làm việc onsite nước ngoài (Nhật, Mỹ, EU)",
                'job_type' => 'full_time',
                'positions_count' => 3,
                'salary_type' => 'monthly',
                'salary_amount' => 20000000,
                'shift_type' => 'day',
                'work_start_date' => $now->copy()->subDays(20)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(12)->format('Y-m-d'),
                'work_address' => 'FPT Tower, 10 Phạm Văn Bạch, Tân Bình, TP. Hồ Chí Minh',
                'has_housing' => false,
                'min_age' => 22,
                'max_age' => 35,
                'deadline' => $now->copy()->addDays(30)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 892,
            ],
            // 10. Nhan vien kinh doanh - Vingroup, Ha Noi, active
            [
                'employer_id' => $vingroup->id,
                'title' => 'Nhân viên kinh doanh',
                'description' => "Vị trí: Nhân viên kinh doanh bất động sản tại Vingroup, Hà Nội.\n\nMô tả công việc:\n- Tìm kiếm và phát triển khách hàng tiềm năng\n- Tư vấn, giới thiệu dự án bất động sản Vinhomes\n- Dẫn khách tham quan nhà mẫu, căn hộ\n- Hỗ trợ khách hàng làm hồ sơ mua bán, vay ngân hàng\n- Chăm sóc khách hàng sau bán hàng\n- Đạt KPI doanh số được giao",
                'requirements' => "- Nam/Nữ, tuổi từ 22-35\n- Tốt nghiệp Cao đẳng trở lên\n- Có kỹ năng giao tiếp, thuyết phục tốt\n- Kinh nghiệm bán hàng từ 1 năm (ưu tiên BĐS)\n- Ngoại hình ưa nhìn, tác phong chuyên nghiệp\n- Có phương tiện đi lại",
                'benefits' => "- Lương cơ bản: 8.000.000 - 15.000.000 VNĐ/tháng\n- Hoa hồng bán hàng hấp dẫn (0.5-1% giá trị BĐS)\n- BHXH, BHYT đầy đủ\n- Đào tạo bài bản về sản phẩm và kỹ năng bán hàng\n- Cơ hội thăng tiến nhanh\n- Du lịch nước ngoài cho top sales",
                'job_type' => 'full_time',
                'positions_count' => 4,
                'salary_type' => 'monthly',
                'salary_amount' => 11000000,
                'shift_type' => 'day',
                'work_start_date' => $now->copy()->subDays(14)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(12)->format('Y-m-d'),
                'work_address' => 'Vinhomes Riverside, Long Biên, Hà Nội',
                'has_housing' => false,
                'min_age' => 22,
                'max_age' => 35,
                'deadline' => $now->copy()->addDays(22)->format('Y-m-d'),
                'status' => 'published',
                'view_count' => 634,
            ],
            // 11. Pha che - Pho Xanh, Ha Noi, pending
            [
                'employer_id' => $phoXanh->id,
                'title' => 'Pha chế',
                'description' => "Vị trí: Bartender/Pha chế tại nhà hàng Phố Xanh, Hà Nội.\n\nMô tả công việc:\n- Pha chế các loại cocktail, mocktail, đồ uống\n- Sáng tạo menu đồ uống mới theo mùa\n- Quản lý nguyên liệu và dụng cụ pha chế\n- Tư vấn đồ uống cho khách hàng\n- Duy trì vệ sinh khu vực bar\n- Kiểm soát chất lượng đồ uống",
                'requirements' => "- Nam/Nữ, tuổi từ 20-30\n- Có kinh nghiệm pha chế ít nhất 1 năm\n- Có chứng chỉ pha chế là lợi thế lớn\n- Sáng tạo, có mắt thẩm mỹ\n- Kỹ năng giao tiếp tốt\n- Chịu được áp lực giờ cao điểm",
                'benefits' => "- Lương: 5.000.000 - 7.000.000 VNĐ/tháng\n- Tip từ khách hàng\n- Bao ăn ca\n- BHXH đầy đủ\n- Được đào tạo nâng cao kỹ năng\n- Ca làm linh hoạt",
                'job_type' => 'part_time',
                'positions_count' => 2,
                'salary_type' => 'monthly',
                'salary_amount' => 6000000,
                'shift_type' => 'evening',
                'work_start_date' => $now->copy()->addDays(5)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(6)->format('Y-m-d'),
                'work_address' => '15 Phố Tạ Hiện, Hoàn Kiếm, Hà Nội',
                'has_housing' => false,
                'min_age' => 20,
                'max_age' => 30,
                'deadline' => $now->copy()->addDays(25)->format('Y-m-d'),
                'status' => 'pending',
                'view_count' => 0,
            ],
            // 12. Thuc tap sinh marketing - MegaMart, HCM, pending
            [
                'employer_id' => $megaMart->id,
                'title' => 'Thực tập sinh marketing',
                'description' => "Vị trí: Thực tập sinh Marketing tại MegaMart khu vực TP.HCM.\n\nMô tả công việc:\n- Hỗ trợ triển khai các chiến dịch marketing online/offline\n- Viết content cho fanpage, website\n- Hỗ trợ tổ chức sự kiện khuyến mãi tại cửa hàng\n- Thu thập và phân tích dữ liệu khách hàng\n- Thiết kế hình ảnh đơn giản (banner, poster)\n- Báo cáo hiệu quả các chiến dịch",
                'requirements' => "- Sinh viên năm cuối hoặc mới tốt nghiệp ngành Marketing\n- Có khả năng viết content sáng tạo\n- Sử dụng thành thạo Canva hoặc Photoshop cơ bản\n- Hiểu biết về digital marketing là lợi thế\n- Năng động, sáng tạo, ham học hỏi\n- Có laptop cá nhân",
                'benefits' => "- Trợ cấp: 3.000.000 - 5.000.000 VNĐ/tháng\n- Được mentoring bởi Marketing Manager\n- Cơ hội chuyển chính thức sau thực tập\n- Chứng nhận thực tập\n- Linh hoạt giờ làm\n- Học hỏi quy trình marketing chuyên nghiệp",
                'job_type' => 'temporary',
                'positions_count' => 3,
                'salary_type' => 'monthly',
                'salary_amount' => 4000000,
                'shift_type' => 'day',
                'work_start_date' => $now->copy()->addDays(10)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(3)->format('Y-m-d'),
                'work_address' => '120 Lê Lợi, Quận 1, TP. Hồ Chí Minh',
                'has_housing' => false,
                'min_age' => 20,
                'max_age' => 25,
                'deadline' => $now->copy()->addDays(20)->format('Y-m-d'),
                'status' => 'pending',
                'view_count' => 0,
            ],
            // 13. Nhan vien CSKH - Tiki, HCM, pending
            [
                'employer_id' => $tiki->id,
                'title' => 'Nhân viên chăm sóc khách hàng',
                'description' => "Vị trí: Customer Service tại Tiki Corporation, TP. Hồ Chí Minh.\n\nMô tả công việc:\n- Tiếp nhận và xử lý khiếu nại, yêu cầu của khách hàng qua hotline, chat, email\n- Hỗ trợ khách tra cứu đơn hàng, thông tin sản phẩm\n- Xử lý đơn đổi/trả hàng\n- Ghi nhận và escalate vấn đề phức tạp lên cấp trên\n- Đảm bảo SLA phản hồi khách hàng\n- Báo cáo các vấn đề phát sinh thường gặp",
                'requirements' => "- Nam/Nữ, tuổi từ 20-30\n- Tốt nghiệp Cao đẳng trở lên\n- Giọng nói rõ ràng, dễ nghe\n- Kiên nhẫn, bình tĩnh khi xử lý khiếu nại\n- Sử dụng thành thạo máy tính\n- Có kinh nghiệm CSKH hoặc call center là lợi thế",
                'benefits' => "- Lương: 6.000.000 - 9.000.000 VNĐ/tháng\n- BHXH, BHYT, BHTN\n- Phụ cấp ca đêm\n- Voucher mua hàng Tiki hàng tháng\n- Môi trường làm việc trẻ, năng động\n- Đào tạo kỹ năng chuyên nghiệp",
                'job_type' => 'full_time',
                'positions_count' => 5,
                'salary_type' => 'monthly',
                'salary_amount' => 7500000,
                'shift_type' => 'rotating',
                'work_start_date' => $now->copy()->addDays(7)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(12)->format('Y-m-d'),
                'work_address' => '52 Út Tịch, Tân Bình, TP. Hồ Chí Minh',
                'has_housing' => false,
                'min_age' => 20,
                'max_age' => 30,
                'deadline' => $now->copy()->addDays(18)->format('Y-m-d'),
                'status' => 'pending',
                'view_count' => 0,
            ],
            // 14. Quan ly ca - Sunrise, Da Nang, closed
            [
                'employer_id' => $sunrise->id,
                'title' => 'Quản lý ca',
                'description' => "Vị trí: Shift Manager tại Khách sạn Sunrise, Đà Nẵng.\n\nMô tả công việc:\n- Quản lý, giám sát nhân viên trong ca trực\n- Đảm bảo chất lượng dịch vụ theo tiêu chuẩn khách sạn\n- Xử lý các tình huống phát sinh với khách hàng\n- Lập lịch làm việc cho nhân viên\n- Báo cáo tình hình hoạt động ca trực cho GM\n- Đào tạo, hướng dẫn nhân viên mới",
                'requirements' => "- Nam/Nữ, tuổi từ 25-40\n- Tốt nghiệp Đại học ngành Quản trị Khách sạn hoặc tương đương\n- Có ít nhất 3 năm kinh nghiệm trong ngành khách sạn\n- Có ít nhất 1 năm kinh nghiệm quản lý\n- Tiếng Anh giao tiếp tốt\n- Kỹ năng lãnh đạo và giải quyết vấn đề xuất sắc",
                'benefits' => "- Lương: 10.000.000 - 15.000.000 VNĐ/tháng\n- BHXH, BHYT đầy đủ\n- Bao ăn, phòng nghỉ cho nhân viên xa nhà\n- Thưởng năm 2-3 tháng lương\n- Du lịch công ty\n- Cơ hội đào tạo tại khách sạn đối tác nước ngoài",
                'job_type' => 'full_time',
                'positions_count' => 2,
                'filled_count' => 2,
                'salary_type' => 'monthly',
                'salary_amount' => 12000000,
                'shift_type' => 'rotating',
                'work_start_date' => $now->copy()->subDays(60)->format('Y-m-d'),
                'work_end_date' => $now->copy()->addMonths(12)->format('Y-m-d'),
                'work_address' => '120 Đường Võ Nguyên Giáp, Sơn Trà, Đà Nẵng',
                'has_housing' => true,
                'min_age' => 25,
                'max_age' => 40,
                'deadline' => $now->copy()->subDays(10)->format('Y-m-d'),
                'status' => 'closed',
                'view_count' => 567,
            ],
            // 15. Nhan vien ve sinh - Vingroup, Ha Noi, closed
            [
                'employer_id' => $vingroup->id,
                'title' => 'Nhân viên vệ sinh',
                'description' => "Vị trí: Nhân viên vệ sinh tại các tòa nhà Vincom, Hà Nội.\n\nMô tả công việc:\n- Vệ sinh sàn nhà, kính, cầu thang và khu vực công cộng\n- Vệ sinh nhà vệ sinh, bổ sung vật tư\n- Thu gom và xử lý rác thải\n- Chăm sóc cây xanh khu vực được giao\n- Báo cáo hư hỏng thiết bị, cơ sở vật chất\n- Sử dụng hóa chất vệ sinh đúng quy trình",
                'requirements' => "- Nam/Nữ, tuổi từ 18-50\n- Không yêu cầu kinh nghiệm\n- Sức khỏe tốt, chăm chỉ\n- Trung thực, có ý thức kỷ luật\n- Có thể làm ca sáng (6h-14h) hoặc ca chiều (14h-22h)\n- Ưu tiên ứng viên gần khu vực làm việc",
                'benefits' => "- Lương: 4.000.000 - 5.500.000 VNĐ/tháng\n- BHXH, BHYT theo quy định\n- Phụ cấp chuyên cần\n- Đồng phục, dụng cụ vệ sinh\n- Nghỉ phép đúng luật\n- Thưởng lễ, tết",
                'job_type' => 'part_time',
                'positions_count' => 6,
                'filled_count' => 6,
                'salary_type' => 'monthly',
                'salary_amount' => 4500000,
                'shift_type' => 'flexible',
                'work_start_date' => $now->copy()->subDays(90)->format('Y-m-d'),
                'work_end_date' => $now->copy()->subDays(5)->format('Y-m-d'),
                'work_address' => 'Vincom Center Bà Triệu, Hai Bà Trưng, Hà Nội',
                'has_housing' => false,
                'min_age' => 18,
                'max_age' => 50,
                'deadline' => $now->copy()->subDays(30)->format('Y-m-d'),
                'status' => 'closed',
                'view_count' => 421,
            ],
        ];

        foreach ($jobs as $job) {
            JobPost::create($job);
        }
    }
}
