<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\WorkerProfile;
use App\Models\WorkerSkill;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class WorkerProfileSeeder extends Seeder
{
    public function run(): void
    {
        $password = Hash::make('123456');
        $now = now();

        $workers = [
            [
                'name' => 'Nguyễn Thị Hoa',
                'phone' => '0978100001',
                'email' => 'hoa.nguyen@gmail.com',
                'dob' => '1998-03-15',
                'gender' => 'Nữ',
                'id_card' => '079198003150',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 7',
                'skills' => ['Phục vụ', 'Pha chế'],
                'experience_years' => 2.0,
                'availability' => 'available',
                'rating' => 4.2,
                'education' => 'Trung cấp Nghề',
                'bio' => 'Có kinh nghiệm 2 năm phục vụ nhà hàng và pha chế đồ uống. Nhiệt tình, nhanh nhẹn.',
            ],
            [
                'name' => 'Trần Văn Hùng',
                'phone' => '0978100002',
                'email' => 'hung.tran@gmail.com',
                'dob' => '1995-07-22',
                'gender' => 'Nam',
                'id_card' => '079195007221',
                'city' => 'Hà Nội',
                'district' => 'Cầu Giấy',
                'skills' => ['Lái xe', 'Giao hàng'],
                'experience_years' => 5.0,
                'availability' => 'employed',
                'rating' => 4.5,
                'education' => 'Trung học phổ thông',
                'bio' => 'Lái xe chuyên nghiệp, có bằng B2 và C. Thành thạo đường nội thành Hà Nội.',
            ],
            [
                'name' => 'Lê Thị Thanh',
                'phone' => '0978100003',
                'email' => 'thanh.le@gmail.com',
                'dob' => '2000-11-10',
                'gender' => 'Nữ',
                'id_card' => '079200011101',
                'city' => 'Đà Nẵng',
                'district' => 'Sơn Trà',
                'skills' => ['Dọn phòng', 'Giặt ủi'],
                'experience_years' => 1.5,
                'availability' => 'available',
                'rating' => 3.8,
                'education' => 'Trung học cơ sở',
                'bio' => 'Nhân viên dọn phòng khách sạn, cẩn thận và chăm chỉ.',
            ],
            [
                'name' => 'Phạm Đức Mạnh',
                'phone' => '0978100004',
                'email' => 'manh.pham@gmail.com',
                'dob' => '1993-01-05',
                'gender' => 'Nam',
                'id_card' => '079193001051',
                'city' => 'Hồ Chí Minh',
                'district' => 'Bình Tân',
                'skills' => ['Bảo vệ'],
                'experience_years' => 7.0,
                'availability' => 'available',
                'rating' => 4.0,
                'education' => 'Trung học phổ thông',
                'bio' => 'Có chứng chỉ nghiệp vụ bảo vệ. 7 năm kinh nghiệm bảo vệ tòa nhà và khu công nghiệp.',
            ],
            [
                'name' => 'Hoàng Thị Mai',
                'phone' => '0978100005',
                'email' => 'mai.hoang@gmail.com',
                'dob' => '1997-09-28',
                'gender' => 'Nữ',
                'id_card' => '079197009281',
                'city' => 'Hà Nội',
                'district' => 'Thanh Xuân',
                'skills' => ['Bán hàng', 'CRM'],
                'experience_years' => 3.0,
                'availability' => 'available',
                'rating' => 4.3,
                'education' => 'Cao đẳng Thương mại',
                'bio' => 'Nhân viên bán hàng năng động, có khả năng tư vấn sản phẩm tốt. Sử dụng thành thạo phần mềm CRM.',
            ],
            [
                'name' => 'Vũ Minh Quang',
                'phone' => '0978100006',
                'email' => 'quang.vu@gmail.com',
                'dob' => '1996-05-12',
                'gender' => 'Nam',
                'id_card' => '079196005121',
                'city' => 'Nha Trang',
                'district' => 'Vĩnh Hải',
                'skills' => ['Kỹ thuật điện', 'Sửa chữa'],
                'experience_years' => 4.0,
                'availability' => 'employed',
                'rating' => 4.6,
                'education' => 'Trung cấp Kỹ thuật Điện',
                'bio' => 'Kỹ thuật viên điện dân dụng và công nghiệp. Có thể sửa chữa và bảo trì hệ thống điện.',
            ],
            [
                'name' => 'Đặng Thị Linh',
                'phone' => '0978100007',
                'email' => 'linh.dang@gmail.com',
                'dob' => '2001-08-17',
                'gender' => 'Nữ',
                'id_card' => '079201008171',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 1',
                'skills' => ['Kế toán', 'Excel', 'SAP'],
                'experience_years' => 1.0,
                'availability' => 'available',
                'rating' => 3.9,
                'education' => 'Đại học Kinh tế',
                'bio' => 'Cử nhân Kế toán, thành thạo Excel và SAP. Mong muốn tìm việc thời vụ trong lĩnh vực kế toán.',
            ],
            [
                'name' => 'Ngô Văn Tài',
                'phone' => '0978100008',
                'email' => 'tai.ngo@gmail.com',
                'dob' => '1994-12-03',
                'gender' => 'Nam',
                'id_card' => '079194012031',
                'city' => 'Hải Phòng',
                'district' => 'Ngô Quyền',
                'skills' => ['Phục vụ', 'Lễ tân'],
                'experience_years' => 6.0,
                'availability' => 'available',
                'rating' => 4.4,
                'education' => 'Cao đẳng Du lịch',
                'bio' => 'Nhân viên lễ tân khách sạn 4 sao, giao tiếp tiếng Anh cơ bản. Kỹ năng chăm sóc khách hàng tốt.',
            ],
            [
                'name' => 'Bùi Thị Phương',
                'phone' => '0978100009',
                'email' => 'phuong.bui@gmail.com',
                'dob' => '1999-04-20',
                'gender' => 'Nữ',
                'id_card' => '079199004201',
                'city' => 'Đà Nẵng',
                'district' => 'Hải Châu',
                'skills' => ['Phục vụ', 'Dọn phòng'],
                'experience_years' => 2.5,
                'availability' => 'unavailable',
                'rating' => 3.7,
                'education' => 'Trung học phổ thông',
                'bio' => 'Có kinh nghiệm làm việc tại resort và nhà hàng. Sẵn sàng làm ca linh hoạt.',
            ],
            [
                'name' => 'Lý Văn Sơn',
                'phone' => '0978100010',
                'email' => 'son.ly@gmail.com',
                'dob' => '1992-06-30',
                'gender' => 'Nam',
                'id_card' => '079192006301',
                'city' => 'Hồ Chí Minh',
                'district' => 'Thủ Đức',
                'skills' => ['Lái xe', 'Bốc xếp'],
                'experience_years' => 8.0,
                'availability' => 'available',
                'rating' => 4.1,
                'education' => 'Trung học phổ thông',
                'bio' => 'Tài xế xe tải có bằng C, kinh nghiệm giao hàng nội thành và liên tỉnh.',
            ],
            [
                'name' => 'Trương Thị Hạnh',
                'phone' => '0978100011',
                'email' => 'hanh.truong@gmail.com',
                'dob' => '1998-02-14',
                'gender' => 'Nữ',
                'id_card' => '079198002141',
                'city' => 'Hà Nội',
                'district' => 'Đống Đa',
                'skills' => ['Pha chế', 'Phục vụ'],
                'experience_years' => 3.5,
                'availability' => 'available',
                'rating' => 4.7,
                'education' => 'Trung cấp Nghề',
                'bio' => 'Bartender chuyên nghiệp, có chứng chỉ pha chế quốc tế. Sáng tạo menu đồ uống.',
            ],
            [
                'name' => 'Đoàn Văn Thắng',
                'phone' => '0978100012',
                'email' => 'thang.doan@gmail.com',
                'dob' => '1990-10-08',
                'gender' => 'Nam',
                'id_card' => '079190010081',
                'city' => 'Nha Trang',
                'district' => 'Vĩnh Phước',
                'skills' => ['Bảo vệ', 'Giám sát an ninh'],
                'experience_years' => 10.0,
                'availability' => 'employed',
                'rating' => 4.8,
                'education' => 'Trung học phổ thông',
                'bio' => 'Trưởng ca bảo vệ 10 năm kinh nghiệm. Đã qua đào tạo nghiệp vụ PCCC.',
            ],
            [
                'name' => 'Cao Thị Kim',
                'phone' => '0978100013',
                'email' => 'kim.cao@gmail.com',
                'dob' => '2002-07-25',
                'gender' => 'Nữ',
                'id_card' => '079202007251',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 3',
                'skills' => ['Marketing', 'Content writing'],
                'experience_years' => 0.5,
                'availability' => 'available',
                'rating' => 3.5,
                'education' => 'Đại học Marketing',
                'bio' => 'Sinh viên mới tốt nghiệp ngành Marketing. Có kỹ năng viết content và quản lý mạng xã hội.',
            ],
            [
                'name' => 'Đinh Văn Long',
                'phone' => '0978100014',
                'email' => 'long.dinh@gmail.com',
                'dob' => '1991-03-18',
                'gender' => 'Nam',
                'id_card' => '079191003181',
                'city' => 'Hà Nội',
                'district' => 'Hoàng Mai',
                'skills' => ['Kho vận', 'Kiểm kê'],
                'experience_years' => 9.0,
                'availability' => 'available',
                'rating' => 4.3,
                'education' => 'Trung cấp Nghề',
                'bio' => 'Nhân viên kho chuyên nghiệp, quản lý xuất nhập hàng hóa. Sử dụng phần mềm quản lý kho.',
            ],
            [
                'name' => 'Mai Thị Ngân',
                'phone' => '0978100015',
                'email' => 'ngan.mai@gmail.com',
                'dob' => '1996-11-22',
                'gender' => 'Nữ',
                'id_card' => '079196011221',
                'city' => 'Đà Nẵng',
                'district' => 'Thanh Khê',
                'skills' => ['Nấu ăn', 'Phụ bếp'],
                'experience_years' => 4.5,
                'availability' => 'available',
                'rating' => 4.4,
                'education' => 'Trung cấp Nấu ăn',
                'bio' => 'Đầu bếp phụ tại nhà hàng Việt Nam, chuyên món Việt và Á. Có chứng chỉ vệ sinh an toàn thực phẩm.',
            ],
            [
                'name' => 'Phan Văn Dũng',
                'phone' => '0978100016',
                'email' => 'dung.phan@gmail.com',
                'dob' => '1988-09-05',
                'gender' => 'Nam',
                'id_card' => '079188009051',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 12',
                'skills' => ['Sửa chữa', 'Bảo trì', 'Điện nước'],
                'experience_years' => 10.0,
                'availability' => 'employed',
                'rating' => 5.0,
                'education' => 'Trung cấp Cơ điện',
                'bio' => 'Thợ sửa chữa đa năng: điện, nước, máy lạnh, thiết bị gia dụng. Có đội ngũ hỗ trợ.',
            ],
            [
                'name' => 'Tô Thị Yến',
                'phone' => '0978100017',
                'email' => 'yen.to@gmail.com',
                'dob' => '2003-01-30',
                'gender' => 'Nữ',
                'id_card' => '079203001301',
                'city' => 'Hải Phòng',
                'district' => 'Lê Chân',
                'skills' => ['Bán hàng', 'Tư vấn'],
                'experience_years' => 0.0,
                'availability' => 'available',
                'rating' => 3.5,
                'education' => 'Trung học phổ thông',
                'bio' => 'Sinh viên năm cuối, tìm việc thời vụ bán hàng. Hoạt bát, giao tiếp tốt.',
            ],
            [
                'name' => 'Hồ Văn Kiên',
                'phone' => '0978100018',
                'email' => 'kien.ho@gmail.com',
                'dob' => '1995-08-11',
                'gender' => 'Nam',
                'id_card' => '079195008111',
                'city' => 'Hà Nội',
                'district' => 'Long Biên',
                'skills' => ['CNTT', 'Sửa máy tính'],
                'experience_years' => 5.0,
                'availability' => 'unavailable',
                'rating' => 4.6,
                'education' => 'Đại học Công nghệ Thông tin',
                'bio' => 'Kỹ thuật viên IT, sửa chữa phần cứng và cài đặt phần mềm. Hỗ trợ kỹ thuật từ xa.',
            ],
            [
                'name' => 'Lương Thị Oanh',
                'phone' => '0978100019',
                'email' => 'oanh.luong@gmail.com',
                'dob' => '1997-12-19',
                'gender' => 'Nữ',
                'id_card' => '079197012191',
                'city' => 'Nha Trang',
                'district' => 'Ninh Hòa',
                'skills' => ['Giặt ủi', 'Dọn phòng', 'Nấu ăn'],
                'experience_years' => 3.0,
                'availability' => 'available',
                'rating' => 4.0,
                'education' => 'Trung học cơ sở',
                'bio' => 'Nhân viên housekeeping khách sạn 3 sao. Có thể nấu ăn và phục vụ tiệc.',
            ],
            [
                'name' => 'Trịnh Văn Phúc',
                'phone' => '0978100020',
                'email' => 'phuc.trinh@gmail.com',
                'dob' => '1994-04-07',
                'gender' => 'Nam',
                'id_card' => '079194004071',
                'city' => 'Hồ Chí Minh',
                'district' => 'Gò Vấp',
                'skills' => ['Giao hàng', 'Lái xe máy'],
                'experience_years' => 6.0,
                'availability' => 'available',
                'rating' => 4.2,
                'education' => 'Trung học phổ thông',
                'bio' => 'Shipper kinh nghiệm, thông thạo đường Sài Gòn. Có xe máy riêng, sẵn sàng làm ngay.',
            ],
        ];

        // Skill levels mapping
        $skillLevels = ['beginner', 'intermediate', 'advanced', 'expert'];

        foreach ($workers as $w) {
            // Create user with role worker
            $user = User::create([
                'name' => $w['name'],
                'email' => $w['email'],
                'phone' => $w['phone'],
                'password' => $password,
                'role' => 'worker',
                'status' => 'active',
                'email_verified_at' => $now,
                'last_login_at' => $now->copy()->subDays(rand(0, 14)),
            ]);

            // Create worker profile
            $profile = WorkerProfile::create([
                'user_id' => $user->id,
                'full_name' => $w['name'],
                'date_of_birth' => $w['dob'],
                'gender' => $w['gender'],
                'id_card_number' => $w['id_card'],
                'permanent_address' => $w['district'] . ', ' . $w['city'],
                'current_address' => $w['district'] . ', ' . $w['city'],
                'city' => $w['city'],
                'district' => $w['district'],
                'emergency_contact_name' => 'Người thân ' . explode(' ', $w['name'])[count(explode(' ', $w['name'])) - 1],
                'emergency_contact_phone' => '09' . rand(10000000, 99999999),
                'bank_name' => collect(['Vietcombank', 'Techcombank', 'BIDV', 'Agribank', 'MB Bank', 'VPBank'])->random(),
                'bank_account' => (string) rand(1000000000, 9999999999),
                'bank_holder' => strtoupper($this->removeDiacritics($w['name'])),
                'needs_housing' => rand(0, 1),
                'ekyc_status' => 'verified',
                'skills' => json_encode($w['skills']),
                'experience_years' => $w['experience_years'],
                'education' => $w['education'],
                'bio' => $w['bio'],
                'availability_status' => $w['availability'],
                'rating' => $w['rating'],
                'review_count' => rand(3, 25),
                'desired_job_types' => json_encode($w['skills']),
                'desired_locations' => json_encode([$w['city']]),
                'desired_salary' => rand(4, 15) * 1000000,
                'ekyc_verified_at' => $now->copy()->subDays(rand(10, 60)),
            ]);

            // Create worker skills
            foreach ($w['skills'] as $index => $skillName) {
                $expYears = min($w['experience_years'], rand(1, (int) max(1, $w['experience_years'])));
                $levelIndex = min(3, (int) floor($expYears / 2));

                WorkerSkill::create([
                    'worker_profile_id' => $profile->id,
                    'skill_name' => $skillName,
                    'level' => $skillLevels[$levelIndex],
                    'years' => round($expYears, 1),
                ]);
            }
        }
    }

    /**
     * Remove Vietnamese diacritics for bank holder name.
     */
    private function removeDiacritics(string $str): string
    {
        $search = [
            'à', 'á', 'ạ', 'ả', 'ã', 'â', 'ầ', 'ấ', 'ậ', 'ẩ', 'ẫ', 'ă', 'ằ', 'ắ', 'ặ', 'ẳ', 'ẵ',
            'è', 'é', 'ẹ', 'ẻ', 'ẽ', 'ê', 'ề', 'ế', 'ệ', 'ể', 'ễ',
            'ì', 'í', 'ị', 'ỉ', 'ĩ',
            'ò', 'ó', 'ọ', 'ỏ', 'õ', 'ô', 'ồ', 'ố', 'ộ', 'ổ', 'ỗ', 'ơ', 'ờ', 'ớ', 'ợ', 'ở', 'ỡ',
            'ù', 'ú', 'ụ', 'ủ', 'ũ', 'ư', 'ừ', 'ứ', 'ự', 'ử', 'ữ',
            'ỳ', 'ý', 'ỵ', 'ỷ', 'ỹ',
            'đ',
            'À', 'Á', 'Ạ', 'Ả', 'Ã', 'Â', 'Ầ', 'Ấ', 'Ậ', 'Ẩ', 'Ẫ', 'Ă', 'Ằ', 'Ắ', 'Ặ', 'Ẳ', 'Ẵ',
            'È', 'É', 'Ẹ', 'Ẻ', 'Ẽ', 'Ê', 'Ề', 'Ế', 'Ệ', 'Ể', 'Ễ',
            'Ì', 'Í', 'Ị', 'Ỉ', 'Ĩ',
            'Ò', 'Ó', 'Ọ', 'Ỏ', 'Õ', 'Ô', 'Ồ', 'Ố', 'Ộ', 'Ổ', 'Ỗ', 'Ơ', 'Ờ', 'Ớ', 'Ợ', 'Ở', 'Ỡ',
            'Ù', 'Ú', 'Ụ', 'Ủ', 'Ũ', 'Ư', 'Ừ', 'Ứ', 'Ự', 'Ử', 'Ữ',
            'Ỳ', 'Ý', 'Ỵ', 'Ỷ', 'Ỹ',
            'Đ',
        ];

        $replace = [
            'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
            'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e',
            'i', 'i', 'i', 'i', 'i',
            'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o',
            'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u',
            'y', 'y', 'y', 'y', 'y',
            'd',
            'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
            'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E',
            'I', 'I', 'I', 'I', 'I',
            'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O',
            'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U',
            'Y', 'Y', 'Y', 'Y', 'Y',
            'D',
        ];

        return str_replace($search, $replace, $str);
    }
}
